export const USER_LOGIN = {
  CALL_API: 'USER_LOGIN_CALL_API',
  START: 'USER_LOGIN_API_START',
  SUCCESS: 'USER_LOGIN_API_SUCCESS',
  FAILED: 'USER_LOGIN_API_FAILED',
  END: 'USER_LOGIN_API_END',
};

export const RESET_STORE = 'RESET_STORE';
