export const IMAGES = {
  EyeIcon: require('../assets/images/EyeIcon/EyeIcon.png'),
  logo: require('../assets/images/logo/logo.png'),
  chevronRight: require('../assets/images/chevronRight/chevronRight.png'),
  chevronLeft: require('../assets/images/chevronLeft/chevronLeft.png'),
  bx_home: require('../assets/images/bx_home/bx_home.png'),
  uil_calender: require('../assets/images/uil_calender/uil_calender.png'),
  uiw_date: require('../assets/images/uiw_date/uiw_date.png'),
  uil_invoice: require('../assets/images/uil_invoice/uil_invoice.png'),
  itemImg: require('../assets/images/itemImg/itemImg.png'),
  medicalImg: require('../assets/images/medicalImg/medicalImg.png'),
  settings: require('../assets/images/settings/settings.png'),
  tabler_message: require('../assets/images/tabler_message/tabler_message.png'),
  uilchart_lines: require('../assets/images/uilchart_lines/uilchart_lines.png'),
  shareOutlined: require('../assets/images/shareOutlined/shareOutlined.png'),
  cil_history: require('../assets/images/cil_history/cil_history.png'),
  arrow_back: require('../assets/images/arrow_back/arrow_back.png'),
  arrow_down: require('../assets/images/arrow_down/arrow_down.png'),
  search: require('../assets/icons/search/search.png'),
  ci_hamburger_md: require('../assets/icons/ci_hamburger_md/ci_hamburger_md.png'),
};
